# makefile

all:summary3
#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT

summary3:summary3.cpp
	g++ -g -Wall -o summary3 summary3.cpp -framework OPENGL -framework GLUT


.PHONY:clean
clean:
	rm -Rf *.o *.dSYM summary3

