# makefile

all:mainRect

#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT
mainRect:mainRect.c
	gcc -g -Wall -o mainRect mainRect.c -framework OPENGL -framework GLUT

.PHONY:clean
clean:
	rm -Rf *.o *.dSYM mainRect

