# makefile

all:mainQuads

#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT
mainQuads:mainQuads.c
	gcc -g -Wall -o mainQuads mainQuads.c -framework OPENGL -framework GLUT

.PHONY:clean
clean:
	rm -Rf *.o *.dSYM mainQuads

