# makefile

all:summary2
#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT

summary2:summary2.c
	gcc -g -Wall -o summary2 summary2.c -framework OPENGL -framework GLUT


.PHONY:clean
clean:
	rm -Rf *.o *.dSYM summary2

