#!/bin/bash



disorganize:disorganize.c
	gcc   -Wall   -o  disorganize   disorganize.c

main:main.c
	gcc   -Wall   -o  main   main.c


.PHONY:clean
clean:
	-rm   -Rf   *.o*   *.dSYM   *.exe   disorganize    main.c

