# makefile

all:mainTriangleStrip

#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT
mainTriangleStrip:mainTriangleStrip.c
	gcc -g -Wall -o mainTriangleStrip mainTriangleStrip.c -framework OPENGL -framework GLUT

.PHONY:clean
clean:
	rm -Rf *.o *.dSYM mainTriangleStrip

