# makefile

all:mainQuadStrip

#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT
mainQuadStrip:mainQuadStrip.c
	gcc -g -Wall -o mainQuadStrip mainQuadStrip.c -framework OPENGL -framework GLUT


.PHONY:clean
clean:
	rm -Rf *.o *.dSYM mainQuadStrip

