# makefile

all:mainTriangle
#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT

mainTriangle:mainTriangle.c
	gcc -g -Wall -o mainTriangle mainTriangle.c -framework OPENGL -framework GLUT


.PHONY:clean
clean:
	rm -Rf *.o *.dSYM mainTriangle

