# makefile

all:mainTriangleFan

#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT
mainTriangleFan:mainTriangleFan.c
	gcc -g -Wall -o mainTriangleFan mainTriangleFan.c -framework OPENGL -framework GLUT

.PHONY:clean
clean:
	rm -Rf *.o *.dSYM mainTriangleFan

