#!/bin/bash

intergerValueRange:intergerValueRange.cpp
	g++   -Wall  -std=c++11   -O3   -o   intergerValueRange    intergerValueRange.cpp



.PHONY:clean
clean:
	-rm   -Rf  *.o*  *.exe  *.dSYM    intergerValueRange
