#!/bin/bash


replaceChinesePunctuation:replaceChinesePunctuation.cpp
	g++   -Wall   -std=c++11   -o   replaceChinesePunctuation    replaceChinesePunctuation.cpp


.PHONY:clean
clean:
	-rm    -Rf    *.o*  *.exe   replaceChinesePunctuation
