#!/bin/bash

####################################################################################################
#
# Designated Struct Initialization is a new feature since  c++20
#
####################################################################################################
main:main.cpp
	g++   -Wall  -std=c++20   -o   main   main.cpp


.PHONY:clean
clean:
	-rm   -Rf  *.o*  *.dSYM  *.exe   main




