#!/bin/bash

# echo 'Hello Shell , in goto script'
# /Users/Edison/work/me/src/github
#



case "${1}" in
    "c")
        cd ~/work/gnu/c/test
        echo "Now u are @   ==> `pwd`"
        ;;
    "cpp")
        cd ~/work/gnu/cpp/test
        echo "Now u are @   ==> `pwd`"
        ;;
    "cpp1")
        cd ~/work/gnu/cpp/test/test1
        echo "Now u are @   ==> `pwd`"
        ;;
    "cpp2")
        cd ~/work/gnu/cpp/test/test2
        echo "Now u are @   ==> `pwd`"
        ;;
    "cpp3")
        cd ~/work/gnu/cpp/test/test3
        echo "Now u are @   ==> `pwd`"
        ;;
    "cpp4")
        cd ~/work/gnu/cpp/test/test4
        echo "Now u are @   ==> `pwd`"
        ;;
    "cpp5")
        cd ~/work/gnu/cpp/test/test5
        echo "Now u are @   ==> `pwd`"
        ;;
    "cpptools")
        cd ~/work/cppTools
        echo "Now u are @   ==> `pwd`"
        ;;
    "doc")
        cd ~/work/doc
        echo "Now u are @   ==> `pwd`"
        ;;
    "git")
        cd ~/work/gitrepo/myrepo/Vector
        echo "Now u are @   ==> `pwd`"
        ;;
    "help" | "" | *)
        echo "==========================================================="
        echo "           No Matched tag, Please see the following help   "
        echo "==========================================================="
        echo "c          -->   ~/work/gnu/c/test"
        echo "cpp        -->   ~/work/gnu/cpp/test"
        echo "cpp1       -->   ~/work/gnu/cpp/test/test1"
        echo "cpp2       -->   ~/work/gnu/cpp/test/test2"
        echo "cpp3       -->   ~/work/gnu/cpp/test/test3"
        echo "cpp4       -->   ~/work/gnu/cpp/test/test4"
        echo "cpp5       -->   ~/work/gnu/cpp/test/test5"
        echo "cpptools   -->   ~/work/cppTools"
        echo "doc        -->   ~/work/doc"
        echo "git        -->   ~/work/gitrepo/myrepo/Vector"
        ;;
esac


