# makefile

all:mainPolygon

#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT

mainPolygon:mainPolygon.c
	gcc -g -Wall -o mainPolygon mainPolygon.c -framework OPENGL -framework GLUT

.PHONY:clean
clean:
	rm -Rf *.o *.dSYM mainPolygon

