#!/bin/bash 



all:binaryCmp 
	

binaryCmp:binaryCmp.cpp
	g++  -Wall -std=c++11    -O3   -o  binaryCmp   binaryCmp.cpp




.PHONY:clean
clean:
	-rm   -Rf   *.o    main   *.dSYM   binaryCompare binaryCmp
