# makefile

all:summary1
#gcc -g -Wall -o main main.c -framework OPENGL -framework GLUT

summary1:summary1.c
	gcc -g -Wall -o summary1 summary1.c -framework OPENGL -framework GLUT


.PHONY:clean
clean:
	rm -Rf *.o *.dSYM summary1

