#!/bin/bash

dynamicArray:dynamicArray.cpp
	g++   -Wall  -std=c++11   -o   build/dynamicArray    dynamicArray.cpp



.PHONY:clean
clean:
	-rm  -Rf   build/*.o*  build/*.dSYM  build/*.exe    build/dynamicArray
